"""Refactor trend and formula generation, update insight portal

Revision ID: 059669725075
Revises: 8996b1f36ea0
Create Date: 2025-09-13 15:49:22.911096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059669725075'
down_revision: Union[str, None] = '8996b1f36ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trend_data_ingredient_id_fkey', 'trend_data', type_='foreignkey')
    op.drop_column('trend_data', 'ingredient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_data', sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('trend_data_ingredient_id_fkey', 'trend_data', 'ingredients', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###
