"""create token denylist table

Revision ID: 22cb5f6fe9e5
Revises: e1a8e2725537
Create Date: 2025-09-19 13:37:54.454174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cb5f6fe9e5'
down_revision: Union[str, None] = 'e1a8e2725537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
