"""Drop mock_consumer table

Revision ID: 25fe8c7cf948
Revises: fd8bd7bf8988
Create Date: 2025-09-11 15:03:07.036140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25fe8c7cf948'
down_revision: Union[str, None] = 'fd8bd7bf8988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mock_consumers_email', table_name='mock_consumers')
    op.drop_index('ix_mock_consumers_id', table_name='mock_consumers')
    op.drop_index('ix_mock_consumers_name', table_name='mock_consumers')
    op.drop_table('mock_consumers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_consumers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purchasing_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mock_consumers_pkey')
    )
    op.create_index('ix_mock_consumers_name', 'mock_consumers', ['name'], unique=False)
    op.create_index('ix_mock_consumers_id', 'mock_consumers', ['id'], unique=False)
    op.create_index('ix_mock_consumers_email', 'mock_consumers', ['email'], unique=False)
    # ### end Alembic commands ###
