"""Remove ai_insight and consumer_insight tables

Revision ID: 26cb089e10b4
Revises: 5ba73badf9a2
Create Date: 2025-09-12 11:27:27.974699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26cb089e10b4'
down_revision: Union[str, None] = '5ba73badf9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insights_id', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_consumer_insights_id', table_name='consumer_insights')
    op.drop_table('consumer_insights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('social_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('insight_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('signal_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['social_post_id'], ['social_posts.id'], name='consumer_insights_social_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='consumer_insights_pkey')
    )
    op.create_index('ix_consumer_insights_id', 'consumer_insights', ['id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trend_data_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('insight_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trend_data_id'], ['trend_data.id'], name='insights_trend_data_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='insights_pkey')
    )
    op.create_index('ix_insights_id', 'insights', ['id'], unique=False)
    # ### end Alembic commands ###
