"""Initial migration

Revision ID: 29e480a9e5d8
Revises: c6abb2b4f77f
Create Date: 2025-01-23 13:29:52.419703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e480a9e5d8'
down_revision: Union[str, None] = 'c6abb2b4f77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
