"""add timestamps to formulas

Revision ID: 2b9a3ff5bd4e
Revises: d651140643bf
Create Date: 2025-11-16 22:07:49.882143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9a3ff5bd4e'
down_revision: Union[str, None] = 'd651140643bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('formulas', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulas', 'updated_at')
    op.drop_column('formulas', 'created_at')
    # ### end Alembic commands ###
