"""add enrichment status to ingredient

Revision ID: 2e8877a9ee47
Revises: 72f5889e5d6e
Create Date: 2025-10-04 11:12:44.728213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8877a9ee47'
down_revision: Union[str, None] = '72f5889e5d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('enrichment_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('ingredients', sa.Column('enrichment_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'enrichment_error')
    op.drop_column('ingredients', 'enrichment_status')
    # ### end Alembic commands ###
