"""Implement news features and bookmarking

Revision ID: 5ba73badf9a2
Revises: 25fe8c7cf948
Create Date: 2025-09-11 15:19:35.138304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba73badf9a2'
down_revision: Union[str, None] = '25fe8c7cf948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarked_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_feed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_feed_id'], ['news_feed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarked_news_id'), 'bookmarked_news', ['id'], unique=False)
    op.add_column('news_feed', sa.Column('image', sa.String(), nullable=True))
    op.add_column('news_feed', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_feed', 'views')
    op.drop_column('news_feed', 'image')
    op.drop_index(op.f('ix_bookmarked_news_id'), table_name='bookmarked_news')
    op.drop_table('bookmarked_news')
    # ### end Alembic commands ###
