"""Add slug to TrendData model

Revision ID: 5dddb3743429
Revises: bcc9036935c0
Create Date: 2025-09-15 22:56:40.513849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dddb3743429'
down_revision: Union[str, None] = 'bcc9036935c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable=True first
    op.add_column('trend_data', sa.Column('link', sa.String(), nullable=True))
    op.add_column('trend_data', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('trend_data', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('trend_data', sa.Column('pub_date', sa.DateTime(timezone=True), nullable=True))

    # Update existing rows with default values for 'link' and 'slug'
    op.execute("UPDATE trend_data SET link = '' WHERE link IS NULL")
    op.execute("UPDATE trend_data SET slug = 'placeholder-slug-' || id::text WHERE slug IS NULL")

    # Now alter columns to nullable=False
    op.alter_column('trend_data', 'link', existing_type=sa.String(), nullable=False)
    op.alter_column('trend_data', 'slug', existing_type=sa.String(), nullable=False)

    op.alter_column('trend_data', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_trend_data_category', table_name='trend_data')
    op.create_index(op.f('ix_trend_data_slug'), 'trend_data', ['slug'], unique=True)
    op.drop_column('trend_data', 'source_url')
    op.drop_column('trend_data', 'tags')
    op.drop_column('trend_data', 'content')
    op.drop_column('trend_data', 'category')
    op.drop_column('trend_data', 'socials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_data', sa.Column('socials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('trend_data', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trend_data', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trend_data', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('trend_data', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_trend_data_slug'), table_name='trend_data')
    op.create_index('ix_trend_data_category', 'trend_data', ['category'], unique=False)
    op.alter_column('trend_data', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('trend_data', 'pub_date')
    op.drop_column('trend_data', 'description')
    op.drop_column('trend_data', 'slug')
    op.drop_column('trend_data', 'link')
    # ### end Alembic commands ###
