"""fix socials and customer insight models

Revision ID: 6caa5fbe60c9
Revises: 3c887fa8d9d2
Create Date: 2025-09-11 08:49:44.649803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6caa5fbe60c9'
down_revision: Union[str, None] = '3c887fa8d9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
