"""manual create token denylist table

Revision ID: 72f5889e5d6e
Revises: c7683ca7aecc
Create Date: 2025-09-16 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f5889e5d6e'
down_revision = 'c7683ca7aecc' # Set this to the last known good revision
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_denylist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_denylist_id'), 'token_denylist', ['id'], unique=False)
    op.create_index(op.f('ix_token_denylist_jti'), 'token_denylist', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_denylist_jti'), table_name='token_denylist')
    op.drop_index(op.f('ix_token_denylist_id'), table_name='token_denylist')
    op.drop_table('token_denylist')
    # ### end Alembic commands ###