"""add_image_to_ingredient

Revision ID: 795dfdb2c0b2
Revises: 5f662634bb1f
Create Date: 2025-10-17 16:50:27.664636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795dfdb2c0b2'
down_revision: Union[str, None] = '5f662634bb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'image')
    # ### end Alembic commands ###
