"""Add ingredient model

Revision ID: 7b515932bd0e
Revises: edbd0b4ccfc9
Create Date: 2025-09-08 13:33:08.942159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b515932bd0e'
down_revision: Union[str, None] = 'edbd0b4ccfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
