"""Implement many-to-many relationship between Ingredient and Supplier

Revision ID: 8996b1f36ea0
Revises: 26cb089e10b4
Create Date: 2025-09-13 13:35:59.905616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8996b1f36ea0'
down_revision: Union[str, None] = '26cb089e10b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_suppliers',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'supplier_id')
    )
    op.drop_index('ix_social_posts_id', table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_column('ingredients', 'vendor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('social_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('post_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='social_posts_pkey')
    )
    op.create_index('ix_social_posts_id', 'social_posts', ['id'], unique=False)
    op.drop_table('ingredient_suppliers')
    # ### end Alembic commands ###
