"""add slug to news feed and update published_at

Revision ID: ad61e8abbd74
Revises: e4f8bede2e16
Create Date: 2025-09-17 06:57:47.647966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad61e8abbd74'
down_revision: Union[str, None] = 'e4f8bede2e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_feed', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_news_feed_slug'), 'news_feed', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_feed_slug'), table_name='news_feed')
    op.drop_column('news_feed', 'slug')
    # ### end Alembic commands ###
