"""remove views column from news_feed table

Revision ID: ae47edd18116
Revises: ad61e8abbd74
Create Date: 2025-09-17 07:25:34.046657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae47edd18116'
down_revision: Union[str, None] = 'ad61e8abbd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_feed', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_feed', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
