"""Remove cost and cost_per_unit from Ingredient

Revision ID: ae6e5dc9a094
Revises: 059669725075
Create Date: 2025-09-13 21:06:04.186065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6e5dc9a094'
down_revision: Union[str, None] = '059669725075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula_ingredients', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'formula_ingredients', 'suppliers', ['supplier_id'], ['id'])
    op.drop_column('ingredients', 'cost')
    op.drop_column('ingredients', 'cost_per_unit')
    op.add_column('suppliers', sa.Column('price_per_unit', sa.Float(), nullable=True))
    op.drop_column('suppliers', 'price_per_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('price_per_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('suppliers', 'price_per_unit')
    op.add_column('ingredients', sa.Column('cost_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ingredients', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'formula_ingredients', type_='foreignkey')
    op.drop_column('formula_ingredients', 'supplier_id')
    # ### end Alembic commands ###
