"""add formula analysis fields to marketing_copy

Revision ID: bcc9036935c0
Revises: e9160585a954
Create Date: 2025-09-15 10:19:54.868438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc9036935c0'
down_revision: Union[str, None] = 'e9160585a954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_copies', sa.Column('estimated_cost_per_unit', sa.JSON(), nullable=True))
    op.add_column('marketing_copies', sa.Column('batch_cost', sa.JSON(), nullable=True))
    op.add_column('marketing_copies', sa.Column('potential_savings', sa.JSON(), nullable=True))
    op.add_column('marketing_copies', sa.Column('suggestions', sa.JSON(), nullable=True))
    op.add_column('marketing_copies', sa.Column('allergen_alerts', sa.JSON(), nullable=True))
    op.add_column('marketing_copies', sa.Column('sustainability', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_copies', 'sustainability')
    op.drop_column('marketing_copies', 'allergen_alerts')
    op.drop_column('marketing_copies', 'suggestions')
    op.drop_column('marketing_copies', 'potential_savings')
    op.drop_column('marketing_copies', 'batch_cost')
    op.drop_column('marketing_copies', 'estimated_cost_per_unit')
    # ### end Alembic commands ###
