"""Add calories and serving size to marketing copy

Revision ID: c5fc66a4015c
Revises: 191b482a10b0
Create Date: 2025-10-22 09:35:09.503645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fc66a4015c'
down_revision: Union[str, None] = '191b482a10b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_copies', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('marketing_copies', sa.Column('serving_size_per_bottle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_copies', 'serving_size_per_bottle')
    op.drop_column('marketing_copies', 'calories')
    # ### end Alembic commands ###
