"""add cascading delete to user bookmarks

Revision ID: c7683ca7aecc
Revises: 22cb5f6fe9e5
Create Date: 2025-09-19 13:45:38.296725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7683ca7aecc'
down_revision: Union[str, None] = '22cb5f6fe9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookmarked_news_user_id_fkey', 'bookmarked_news', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarked_news', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('bookmarked_suppliers_user_id_fkey', 'bookmarked_suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarked_suppliers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmarked_suppliers', type_='foreignkey')
    op.create_foreign_key('bookmarked_suppliers_user_id_fkey', 'bookmarked_suppliers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'bookmarked_news', type_='foreignkey')
    op.create_foreign_key('bookmarked_news_user_id_fkey', 'bookmarked_news', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
