"""add marketing_copy table

Revision ID: d4a046076b7b
Revises: e53d40c32f43
Create Date: 2025-09-15 09:16:38.220697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a046076b7b'
down_revision: Union[str, None] = 'e53d40c32f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('key_features', sa.JSON(), nullable=True),
    sa.Column('marketing_copy', sa.Text(), nullable=True),
    sa.Column('product_mockup_url', sa.String(), nullable=True),
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_copies_id'), 'marketing_copies', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_copies_product_name'), 'marketing_copies', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_copies_product_name'), table_name='marketing_copies')
    op.drop_index(op.f('ix_marketing_copies_id'), table_name='marketing_copies')
    op.drop_table('marketing_copies')
    # ### end Alembic commands ###
