"""Rename random_suppliers to suppliers_index in marketing copy

Revision ID: d651140643bf
Revises: c5fc66a4015c
Create Date: 2025-10-22 09:50:03.399284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd651140643bf'
down_revision: Union[str, None] = 'c5fc66a4015c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_copies', sa.Column('suppliers_index', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_copies', 'suppliers_index')
    # ### end Alembic commands ###
