"""add category and tags to trend model

Revision ID: e4f8bede2e16
Revises: 5dddb3743429
Create Date: 2025-09-16 20:01:51.662581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f8bede2e16'
down_revision: Union[str, None] = '5dddb3743429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_data', sa.Column('category', sa.String(), nullable=True))
    op.add_column('trend_data', sa.Column('tags', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_trend_data_category'), 'trend_data', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_data_category'), table_name='trend_data')
    op.drop_column('trend_data', 'tags')
    op.drop_column('trend_data', 'category')
    # ### end Alembic commands ###
