"""Update schema for ingredient cost and formula ingredient supplier

Revision ID: e5d930341578
Revises: ae6e5dc9a094
Create Date: 2025-09-13 22:21:11.612440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d930341578'
down_revision: Union[str, None] = 'ae6e5dc9a094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
