"""add nutritional_facts to marketing_copy

Revision ID: e9160585a954
Revises: d4a046076b7b
Create Date: 2025-09-15 10:15:46.063210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9160585a954'
down_revision: Union[str, None] = 'd4a046076b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_copies', sa.Column('nutritional_facts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_copies', 'nutritional_facts')
    # ### end Alembic commands ###
