"""Implement UI alignment changes

Revision ID: fd263bd2c94c
Revises: 33679e937da0
Create Date: 2025-09-11 09:25:10.603432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd263bd2c94c'
down_revision: Union[str, None] = '33679e937da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('product_concept', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('allergies', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('function', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('ingredients', sa.Column('cost_per_unit', sa.Float(), nullable=True))
    op.add_column('trend_data', sa.Column('socials', sa.JSON(), nullable=True))
    op.add_column('trend_data', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trend_data', 'image')
    op.drop_column('trend_data', 'socials')
    op.drop_column('ingredients', 'cost_per_unit')
    op.drop_column('ingredients', 'notes')
    op.drop_column('ingredients', 'function')
    op.drop_column('ingredients', 'allergies')
    op.drop_column('ingredients', 'unit')
    op.drop_column('ingredients', 'weight')
    op.drop_column('formulas', 'product_concept')
    # ### end Alembic commands ###
