"""Implement ingredient ingestion flow

Revision ID: fd8bd7bf8988
Revises: 58ced9d5f460
Create Date: 2025-09-11 14:50:18.007943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8bd7bf8988'
down_revision: Union[str, None] = '58ced9d5f460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_ingredients_slug'), 'ingredients', ['slug'], unique=True)
    op.drop_column('ingredients', 'notes')
    op.add_column('trend_data', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trend_data', 'ingredients', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trend_data', type_='foreignkey')
    op.drop_column('trend_data', 'ingredient_id')
    op.add_column('ingredients', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ingredients_slug'), table_name='ingredients')
    op.drop_column('ingredients', 'slug')
    # ### end Alembic commands ###
